### ISSUE TITLE
Any chance of a Readme on how to get the basic config for aspcore working?

### ISSUE THREAD

**Issue by SkyCatcher2** [awinnen/ExpertPriceCrawler#1]
Thanks for the hard work. The console app works great, but I wanted to see if I can get the asp core projects working on my local IIS so I can do my own searches. I have no experience with asp or razor so my head hurts. Running the .web on IIS at least displays the site (after adding a few things to VS), but it doesn´t do any actual crawling or logging. I have no clue how to get it to produce a log or set settings like the smtp for example. Any chance you are going to write up a short readme for the .web app?

**Comment by awinnen** [comment]
Sure i can do.
Actually, the webapp was never intended to be used by others than me :P Therefore it might not be obvious what needs to be done to get it working.

How did you deploy the App to IIS? using Visual Studio 'Publish' Dialog?
Is there any chance you can use docker to let the App run? Thats much easier.

**Comment by SkyCatcher2** [comment]
I see :D Yes, I just published it to the IIS Server with VS2022. I can run docker, sure. 

The main reason I would like to run the web app is because I’m lazy and RDP into my desktop from my phone and run the console there. The web app parses the links and shows if the product is demo or new, which makes looking up items so much nicer. 

I wouldn’t mind paying a „donation“ fee for a working web app since you put in the work and it makes my life easier.

**Comment by awinnen** [comment]
I added Instructions for usage with docker to Readme.md
I will add Information for IIS, too  but it will take some time because i need to try ist out myself.

**Comment by SkyCatcher2** [comment]
Thanks, I tried it with docker desktop and wsl2 but end up with:

`System.ArgumentOutOfRangeException: The relative expiration value must be positive. (Parameter 'AbsoluteExpirationRelativeToNow')
Actual value was 00:00:00.
   at Microsoft.Extensions.Caching.Memory.CacheEntry.set_AbsoluteExpirationRelativeToNow(Nullable`1 value)
   at ExpertPriceCrawler.BrowserCrawler.<>c__DisplayClass5_0.<<CollectPrices>b__0>d.MoveNext() in /src/ExpertPriceCrawler/BrowserCrawler.cs:line 24`

which is 
   e.AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(configuration.MemoryCacheMinutes);

I thought it may be the container so I added -TZ to the run command to change to the correct time, but that wasn't it.

**Comment by awinnen** [comment]
ah, sorry. just use a positive number in the expertpricecrawler.env file for Options.MemoryCacheMinutes

i updated the example in readme.md

**Comment by SkyCatcher2** [comment]
It works :)
Thank you very much for your help.

Do you accept donations?

**Comment by awinnen** [comment]
Great ;)

just use the paypal donate button on https://expertpricecrawler.cluster.the.mind-blowing.dev/Queue ;)

**Comment by SkyCatcher2** [comment]
Done, thanks again
